2022-10-15 19:22:42,434 INFO    MainThread:40031 [wandb_setup.py:_flush():68] Configure stats pid to 40031
2022-10-15 19:22:42,434 INFO    MainThread:40031 [wandb_setup.py:_flush():68] Loading settings from /Users/christianjensen/.config/wandb/settings
2022-10-15 19:22:42,434 INFO    MainThread:40031 [wandb_setup.py:_flush():68] Loading settings from /Users/christianjensen/Library/CloudStorage/OneDrive-UniversityofCopenhagen/2 - Projects/NLP Course/NLP-2022/wandb/settings
2022-10-15 19:22:42,434 INFO    MainThread:40031 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True', 'project': 'nlp_course_project'}
2022-10-15 19:22:42,434 INFO    MainThread:40031 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-10-15 19:22:42,434 INFO    MainThread:40031 [wandb_init.py:_log_setup():476] Logging user logs to /Users/christianjensen/Library/CloudStorage/OneDrive-UniversityofCopenhagen/2 - Projects/NLP Course/NLP-2022/wandb/run-20221015_192242-qo5smxpu/logs/debug.log
2022-10-15 19:22:42,434 INFO    MainThread:40031 [wandb_init.py:_log_setup():477] Logging internal logs to /Users/christianjensen/Library/CloudStorage/OneDrive-UniversityofCopenhagen/2 - Projects/NLP Course/NLP-2022/wandb/run-20221015_192242-qo5smxpu/logs/debug-internal.log
2022-10-15 19:22:42,434 INFO    MainThread:40031 [wandb_init.py:_jupyter_setup():426] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x28b8d6f10>
2022-10-15 19:22:42,435 INFO    MainThread:40031 [wandb_init.py:init():516] calling init triggers
2022-10-15 19:22:42,435 INFO    MainThread:40031 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2022-10-15 19:22:42,435 INFO    MainThread:40031 [wandb_init.py:init():569] starting backend
2022-10-15 19:22:42,435 INFO    MainThread:40031 [wandb_init.py:init():573] setting up manager
2022-10-15 19:22:42,439 INFO    MainThread:40031 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-10-15 19:22:42,441 INFO    MainThread:40031 [wandb_init.py:init():580] backend started and connected
2022-10-15 19:22:42,450 INFO    MainThread:40031 [wandb_run.py:_label_probe_notebook():1098] probe notebook
2022-10-15 19:22:42,450 INFO    MainThread:40031 [wandb_run.py:_label_probe_notebook():1108] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-10-15 19:22:42,450 INFO    MainThread:40031 [wandb_init.py:init():658] updated telemetry
2022-10-15 19:29:03,872 WARNING MainThread:40031 [wandb_init.py:init():1097] interrupted
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1076, in init
    run = wi.init()
  File "/opt/homebrew/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 675, in init
    run._populate_git_info()
  File "/opt/homebrew/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 673, in _populate_git_info
    self._remote_url, self._commit = repo.remote_url, repo.last_commit
  File "/opt/homebrew/lib/python3.9/site-packages/wandb/sdk/lib/git.py", line 88, in last_commit
    if not self.repo.head or not self.repo.head.is_valid():
  File "/opt/homebrew/lib/python3.9/site-packages/git/refs/symbolic.py", line 378, in is_valid
    self.object
  File "/opt/homebrew/lib/python3.9/site-packages/git/refs/symbolic.py", line 210, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "/opt/homebrew/lib/python3.9/site-packages/git/refs/symbolic.py", line 151, in dereference_recursive
    hexsha, ref_path = cls._get_ref_info(repo, ref_path)
  File "/opt/homebrew/lib/python3.9/site-packages/git/refs/symbolic.py", line 201, in _get_ref_info
    return cls._get_ref_info_helper(repo, ref_path)
  File "/opt/homebrew/lib/python3.9/site-packages/git/refs/symbolic.py", line 166, in _get_ref_info_helper
    value = fp.read().rstrip()
KeyboardInterrupt
2022-10-15 19:29:09,732 WARNING MsgRouterThr:40031 [router.py:message_loop():77] message_loop has been closed
